repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
    exclude: pyproject.toml
  - id: check-added-large-files
  - id: mixed-line-ending
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.19
  hooks:
  - id: mdformat
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
    exclude: pyproject.toml
- repo: https://gitlab.com/bmares/check-json5 # JSON5 allows comments and trailing commas in JSON files
  rev: v1.0.0
  hooks:
  - id: check-json5
